<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
     public function run(): void
    {
        $countries = [
            /*["name" => "Afghanistan", "code" => "AF", "phone_code" => "+93", "masking" => "999 999 9999"],
            ["name" => "Îles Åland", "code" => "AX", "phone_code" => "", "masking" => ""],
            ["name" => "Albanie", "code" => "AL", "phone_code" => "", "masking" => ""],
            ["name" => "Algérie", "code" => "DZ", "phone_code" => "", "masking" => ""],
            ["name" => "Samoa américaines", "code" => "AS", "phone_code" => "", "masking" => ""],
            ["name" => "AndorrA", "code" => "AD", "phone_code" => "", "masking" => ""],
            ["name" => "Angola", "code" => "AO", "phone_code" => "", "masking" => ""],
            ["name" => "Anguilla", "code" => "AI", "phone_code" => "", "masking" => ""],
            ["name" => "Antarctique", "code" => "AQ", "phone_code" => "", "masking" => ""],
            ["name" => "Antigua et Barbuda", "code" => "AG", "phone_code" => "", "masking" => ""],
            ["name" => "Argentine", "code" => "AR", "phone_code" => "", "masking" => ""],
            ["name" => "Armenie", "code" => "AM", "phone_code" => "", "masking" => ""],
            ["name" => "Aruba", "code" => "AW", "phone_code" => "", "masking" => ""],
            ["name" => "Australie", "code" => "AU", "phone_code" => "", "masking" => ""],
            ["name" => "Autriche", "code" => "AT", "phone_code" => "", "masking" => ""],
            ["name" => "Azerbaïdjan", "code" => "AZ", "phone_code" => "", "masking" => ""],
            ["name" => "Bahamas", "code" => "BS", "phone_code" => "", "masking" => ""],
            ["name" => "Bahreïn", "code" => "BH", "phone_code" => "", "masking" => ""],
            ["name" => "Bangladesh", "code" => "BD", "phone_code" => "", "masking" => ""],
            ["name" => "Barbade", "code" => "BB", "phone_code" => "", "masking" => ""],
            ["name" => "Belarus", "code" => "BY", "phone_code" => "", "masking" => ""],
            ["name" => "Belgique", "code" => "BE", "phone_code" => "", "masking" => ""],
            ["name" => "Belize", "code" => "BZ", "phone_code" => "", "masking" => ""],*/
            ["name" => "Bénin", "code" => "BJ", "phone_code" => "+229", "masking" => "99 99 99 99 99"],
            /*["name" => "Bermudes", "code" => "BM", "phone_code" => "", "masking" => ""],
            ["name" => "Bhoutan", "code" => "BT", "phone_code" => "", "masking" => ""],
            ["name" => "Bolivie", "code" => "BO", "phone_code" => "", "masking" => ""],
            ["name" => "Bosnie-Herzégovine", "code" => "BA", "phone_code" => "", "masking" => ""],
            ["name" => "Botswana", "code" => "BW", "phone_code" => "", "masking" => ""],
            ["name" => "Île Bouvet", "code" => "BV", "phone_code" => "", "masking" => ""],
            ["name" => "Brésil", "code" => "BR", "phone_code" => "", "masking" => ""],
            ["name" => "Territoire britannique de l'océan Indien", "code" => "IO", "phone_code" => "", "masking" => ""],
            ["name" => "Brunei Darussalam", "code" => "BN", "phone_code" => "", "masking" => ""],
            ["name" => "Bulgarie", "code" => "BG", "phone_code" => "", "masking" => ""],
            ["name" => "Burkina Faso", "code" => "BF", "phone_code" => "", "masking" => ""],
            ["name" => "Burundi", "code" => "BI", "phone_code" => "", "masking" => ""],
            ["name" => "Cambodge", "code" => "KH", "phone_code" => "", "masking" => ""],
            ["name" => "Cameroun", "code" => "CM", "phone_code" => "", "masking" => ""],
            ["name" => "Canada", "code" => "CA", "phone_code" => "+ 1", "masking" => "(999) 999-9999"],
            ["name" => "Cap-Vert", "code" => "CV", "phone_code" => "", "masking" => ""],
            ["name" => "Îles Caïmans", "code" => "KY", "phone_code" => "", "masking" => ""],
            ["name" => "République Centrafricaine", "code" => "CF", "phone_code" => "", "masking" => ""],
            ["name" => "Tchad", "code" => "TD", "phone_code" => "", "masking" => ""],
            ["name" => "Chili", "code" => "CL", "phone_code" => "", "masking" => ""],
            ["name" => "Chine", "code" => "CN", "phone_code" => "", "masking" => ""],
            ["name" => "Île Christmas", "code" => "CX", "phone_code" => "", "masking" => ""],
            ["name" => "Îles Cocos (Keeling)", "code" => "CC", "phone_code" => "", "masking" => ""],
            ["name" => "Colombie", "code" => "CO", "phone_code" => "", "masking" => ""],
            ["name" => "Comores", "code" => "KM", "phone_code" => "", "masking" => ""],
            ["name" => "Congo", "code" => "CG", "phone_code" => "", "masking" => ""],
            ["name" => "Congo, République démocratique du", "code" => "CD", "phone_code" => "", "masking" => ""],
            ["name" => "Îles Cook", "code" => "CK", "phone_code" => "", "masking" => ""],
            ["name" => "Costa Rica", "code" => "CR", "phone_code" => "", "masking" => ""],
            ["name" => "Côte d'Ivoire", "code" => "CI", "phone_code" => "", "masking" => ""],
            ["name" => "Croatie", "code" => "HR", "phone_code" => "", "masking" => ""],
            ["name" => "Cuba", "code" => "CU", "phone_code" => "", "masking" => ""],
            ["name" => "Chypre", "code" => "CY", "phone_code" => "", "masking" => ""],
            ["name" => "République tchèque", "code" => "CZ", "phone_code" => "", "masking" => ""],
            ["name" => "Danemark", "code" => "DK", "phone_code" => "", "masking" => ""],
            ["name" => "Djibouti", "code" => "DJ", "phone_code" => "", "masking" => ""],
            ["name" => "Dominique", "code" => "DM", "phone_code" => "", "masking" => ""],
            ["name" => "République dominicaine", "code" => "DO", "phone_code" => "", "masking" => ""],
            ["name" => "Equateur", "code" => "EC", "phone_code" => "", "masking" => ""],
            ["name" => "Égypte", "code" => "EG", "phone_code" => "", "masking" => ""],
            ["name" => "El Salvador", "code" => "SV", "phone_code" => "", "masking" => ""],
            ["name" => "Guinée équatoriale", "code" => "GQ", "phone_code" => "", "masking" => ""],
            ["name" => "Erythrée", "code" => "ER", "phone_code" => "", "masking" => ""],
            ["name" => "Estonie", "code" => "EE", "phone_code" => "", "masking" => ""],
            ["name" => "Ethiopie", "code" => "ET", "phone_code" => "", "masking" => ""],
            ["name" => "Îles Falkland (Malvinas)", "code" => "FK", "phone_code" => "", "masking" => ""],
            ["name" => "Îles Féroé", "code" => "FO", "phone_code" => "", "masking" => ""],
            ["name" => "Fiji", "code" => "FJ", "phone_code" => "", "masking" => ""],
            ["name" => "Finlande", "code" => "FI", "phone_code" => "", "masking" => ""],
            ["name" => "France", "code" => "FR", "phone_code" => "", "masking" => ""],
            ["name" => "Guyane française", "code" => "GF", "phone_code" => "", "masking" => ""],
            ["name" => "Polynésie française", "code" => "PF", "phone_code" => "", "masking" => ""],
            ["name" => "Terres australes françaises", "code" => "TF", "phone_code" => "", "masking" => ""],
            ["name" => "Gabon", "code" => "GA", "phone_code" => "", "masking" => ""],
            ["name" => "Gambie", "code" => "GM", "phone_code" => "", "masking" => ""],
            ["name" => "Georgia", "code" => "GE", "phone_code" => "", "masking" => ""],
            ["name" => "Allemagne", "code" => "DE", "phone_code" => "", "masking" => ""],
            ["name" => "Ghana", "code" => "GH", "phone_code" => "", "masking" => ""],
            ["name" => "Gibraltar", "code" => "GI", "phone_code" => "", "masking" => ""],
            ["name" => "Grèce", "code" => "GR", "phone_code" => "", "masking" => ""],
            ["name" => "Groenland", "code" => "GL", "phone_code" => "", "masking" => ""],
            ["name" => "Grenade", "code" => "GD", "phone_code" => "", "masking" => ""],
            ["name" => "Guadeloupe", "code" => "GP", "phone_code" => "", "masking" => ""],
            ["name" => "Guam", "code" => "GU", "phone_code" => "", "masking" => ""],
            ["name" => "Guatemala", "code" => "GT", "phone_code" => "", "masking" => ""],
            ["name" => "Guernesey", "code" => "GG", "phone_code" => "", "masking" => ""],
            ["name" => "Guinée", "code" => "GN", "phone_code" => "", "masking" => ""],
            ["name" => "Guinée-Bissau", "code" => "GW", "phone_code" => "", "masking" => ""],
            ["name" => "Guyana", "code" => "GY", "phone_code" => "", "masking" => ""],
            ["name" => "Haïti", "code" => "HT", "phone_code" => "", "masking" => ""],
            ["name" => "Ile Heard et îles Mcdonald", "code" => "HM", "phone_code" => "", "masking" => ""],
            ["name" => "Saint-Siège (État de la Cité du Vatican)", "code" => "VA", "phone_code" => "", "masking" => ""],
            ["name" => "Honduras", "code" => "HN", "phone_code" => "", "masking" => ""],
            ["name" => "Hong Kong", "code" => "HK", "phone_code" => "", "masking" => ""],
            ["name" => "Hongrie", "code" => "HU", "phone_code" => "", "masking" => ""],
            ["name" => "Islande", "code" => "IS", "phone_code" => "", "masking" => ""],
            ["name" => "Inde", "code" => "IN", "phone_code" => "", "masking" => ""],
            ["name" => "Indonésie", "code" => "ID", "phone_code" => "", "masking" => ""],
            ["name" => "Iran, République islamique d'", "code" => "IR", "phone_code" => "", "masking" => ""],
            ["name" => "Iraq", "code" => "IQ", "phone_code" => "", "masking" => ""],
            ["name" => "Ireland", "code" => "IE", "phone_code" => "", "masking" => ""],
            ["name" => "Ile de Man", "code" => "IM", "phone_code" => "", "masking" => ""],
            ["name" => "Israël", "code" => "IL", "phone_code" => "", "masking" => ""],
            ["name" => "Italie", "code" => "IT", "phone_code" => "", "masking" => ""],
            ["name" => "Jamaïque", "code" => "JM", "phone_code" => "", "masking" => ""],
            ["name" => "Japon", "code" => "JP", "phone_code" => "", "masking" => ""],
            ["name" => "Jersey", "code" => "JE", "phone_code" => "", "masking" => ""],
            ["name" => "Jordan", "code" => "JO", "phone_code" => "", "masking" => ""],
            ["name" => "Kazakhstan", "code" => "KZ", "phone_code" => "", "masking" => ""],
            ["name" => "Kenya", "code" => "KE", "phone_code" => "", "masking" => ""],
            ["name" => "Kiribati", "code" => "KI", "phone_code" => "", "masking" => ""],
            ["name" => "Corée, République populaire démocratique de", "code" => "KP", "phone_code" => "", "masking" => ""],
            ["name" => "Corée, République de", "code" => "KR", "phone_code" => "", "masking" => ""],
            ["name" => "Koweït", "code" => "KW", "phone_code" => "", "masking" => ""],
            ["name" => "Kirghizistan", "code" => "KG", "phone_code" => "", "masking" => ""],
            ["name" => "République Démocratique Populaire du Laos", "code" => "LA", "phone_code" => "", "masking" => ""],
            ["name" => "Lettonie", "code" => "LV", "phone_code" => "", "masking" => ""],
            ["name" => "Liban", "code" => "LB", "phone_code" => "", "masking" => ""],
            ["name" => "Lesotho", "code" => "LS", "phone_code" => "", "masking" => ""],
            ["name" => "Liberia", "code" => "LR", "phone_code" => "", "masking" => ""],
            ["name" => "Jamahiriya arabe libyenne", "code" => "LY", "phone_code" => "", "masking" => ""],
            ["name" => "Liechtenstein", "code" => "LI", "phone_code" => "", "masking" => ""],
            ["name" => "Lituanie", "code" => "LT", "phone_code" => "", "masking" => ""],
            ["name" => "Luxembourg", "code" => "LU", "phone_code" => "", "masking" => ""],
            ["name" => "Macao", "code" => "MO", "phone_code" => "", "masking" => ""],
            ["name" => "Macédoine, l'ancienne République yougoslave de", "code" => "MK", "phone_code" => "", "masking" => ""],
            ["name" => "Madagascar", "code" => "MG", "phone_code" => "", "masking" => ""],
            ["name" => "Malawi", "code" => "MW", "phone_code" => "", "masking" => ""],
            ["name" => "Malaisie", "code" => "MY", "phone_code" => "", "masking" => ""],
            ["name" => "Maldives", "code" => "MV", "phone_code" => "", "masking" => ""],
            ["name" => "Mali", "code" => "ML", "phone_code" => "", "masking" => ""],
            ["name" => "Malta", "code" => "MT", "phone_code" => "", "masking" => ""],
            ["name" => "Îles Marshall", "code" => "MH", "phone_code" => "", "masking" => ""],
            ["name" => "Martinique", "code" => "MQ", "phone_code" => "", "masking" => ""],
            ["name" => "Mauritanie", "code" => "MR", "phone_code" => "", "masking" => ""],
            ["name" => "Maurice", "code" => "MU", "phone_code" => "", "masking" => ""],
            ["name" => "Mayotte", "code" => "YT", "phone_code" => "", "masking" => ""],
            ["name" => "Mexico", "code" => "MX", "phone_code" => "", "masking" => ""],
            ["name" => "Micronésie, Etats fédérés de", "code" => "FM", "phone_code" => "", "masking" => ""],
            ["name" => "Moldavie, République de", "code" => "MD", "phone_code" => "", "masking" => ""],
            ["name" => "Monaco", "code" => "MC", "phone_code" => "", "masking" => ""],
            ["name" => "Mongolie", "code" => "MN", "phone_code" => "", "masking" => ""],
            ["name" => "Monténégro", "code" => "ME", "phone_code" => "", "masking" => ""],
            ["name" => "Montserrat", "code" => "MS", "phone_code" => "", "masking" => ""],
            ["name" => "Maroc", "code" => "MA", "phone_code" => "", "masking" => ""],
            ["name" => "Mozambique", "code" => "MZ", "phone_code" => "", "masking" => ""],
            ["name" => "Myanmar", "code" => "MM", "phone_code" => "", "masking" => ""],
            ["name" => "Namibie", "code" => "NA", "phone_code" => "", "masking" => ""],
            ["name" => "Nauru", "code" => "NR", "phone_code" => "", "masking" => ""],
            ["name" => "Nepal", "code" => "NP", "phone_code" => "", "masking" => ""],
            ["name" => "Pays-Bas", "code" => "NL", "phone_code" => "", "masking" => ""],
            ["name" => "Antilles néerlandaises", "code" => "AN", "phone_code" => "", "masking" => ""],
            ["name" => "Nouvelle-Calédonie", "code" => "NC", "phone_code" => "", "masking" => ""],
            ["name" => "Nouvelle-Zélande", "code" => "NZ", "phone_code" => "", "masking" => ""],
            ["name" => "Nicaragua", "code" => "NI", "phone_code" => "", "masking" => ""],
            ["name" => "Niger", "code" => "NE", "phone_code" => "", "masking" => ""],
            ["name" => "Nigéria", "code" => "NG", "phone_code" => "", "masking" => ""],
            ["name" => "Niue", "code" => "NU", "phone_code" => "", "masking" => ""],
            ["name" => "Île Norfolk", "code" => "NF", "phone_code" => "", "masking" => ""],
            ["name" => "Iles Mariannes du Nord", "code" => "MP", "phone_code" => "", "masking" => ""],
            ["name" => "Norvège", "code" => "NO", "phone_code" => "", "masking" => ""],
            ["name" => "Oman", "code" => "OM", "phone_code" => "", "masking" => ""],
            ["name" => "Pakistan", "code" => "PK", "phone_code" => "", "masking" => ""],
            ["name" => "Palau", "code" => "PW", "phone_code" => "", "masking" => ""],
            ["name" => "Territoire palestinien occupé", "code" => "PS", "phone_code" => "", "masking" => ""],
            ["name" => "Panama", "code" => "PA", "phone_code" => "", "masking" => ""],
            ["name" => "Papouasie-Nouvelle-Guinée", "code" => "PG", "phone_code" => "", "masking" => ""],
            ["name" => "Paraguay", "code" => "PY", "phone_code" => "", "masking" => ""],
            ["name" => "Pérou", "code" => "PE", "phone_code" => "", "masking" => ""],
            ["name" => "Philippines", "code" => "PH", "phone_code" => "", "masking" => ""],
            ["name" => "Pitcairn", "code" => "PN", "phone_code" => "", "masking" => ""],
            ["name" => "Pologne", "code" => "PL", "phone_code" => "", "masking" => ""],
            ["name" => "Portugal", "code" => "PT", "phone_code" => "", "masking" => ""],
            ["name" => "Puerto Rico", "code" => "PR", "phone_code" => "", "masking" => ""],
            ["name" => "Qatar", "code" => "QA", "phone_code" => "", "masking" => ""],
            ["name" => "Réunion", "code" => "RE", "phone_code" => "", "masking" => ""],
            ["name" => "Roumanie", "code" => "RO", "phone_code" => "", "masking" => ""],
            ["name" => "Russie", "code" => "RU", "phone_code" => "", "masking" => ""],
            ["name" => "RWANDA", "code" => "RW", "phone_code" => "", "masking" => ""],
            ["name" => "Sainte-Hélène", "code" => "SH", "phone_code" => "", "masking" => ""],
            ["name" => "Saint Kitts and Nevis", "code" => "KN", "phone_code" => "", "masking" => ""],
            ["name" => "Sainte-Lucie", "code" => "LC", "phone_code" => "", "masking" => ""],
            ["name" => "Saint Pierre et Miquelon", "code" => "PM", "phone_code" => "", "masking" => ""],
            ["name" => "Saint Vincent et les Grenadines", "code" => "VC", "phone_code" => "", "masking" => ""],
            ["name" => "Samoa", "code" => "WS", "phone_code" => "", "masking" => ""],
            ["name" => "San Marino", "code" => "SM", "phone_code" => "", "masking" => ""],
            ["name" => "Sao Tomé et Principe", "code" => "ST", "phone_code" => "", "masking" => ""],
            ["name" => "Arabie Saoudite", "code" => "SA", "phone_code" => "", "masking" => ""],
            ["name" => "Sénégal", "code" => "SN", "phone_code" => "", "masking" => ""],
            ["name" => "Serbie", "code" => "RS", "phone_code" => "", "masking" => ""],
            ["name" => "Seychelles", "code" => "SC", "phone_code" => "", "masking" => ""],
            ["name" => "Sierra Leone", "code" => "SL", "phone_code" => "", "masking" => ""],
            ["name" => "Singapour", "code" => "SG", "phone_code" => "", "masking" => ""],
            ["name" => "Slovaquie", "code" => "SK", "phone_code" => "", "masking" => ""],
            ["name" => "Slovénie", "code" => "SI", "phone_code" => "", "masking" => ""],
            ["name" => "Iles Salomon", "code" => "SB", "phone_code" => "", "masking" => ""],
            ["name" => "Somalie", "code" => "SO", "phone_code" => "", "masking" => ""],
            ["name" => "Afrique du Sud", "code" => "ZA", "phone_code" => "", "masking" => ""],
            ["name" => "Géorgie du Sud et les îles Sandwich du Sud", "code" => "GS", "phone_code" => "", "masking" => ""],
            ["name" => "Espagne", "code" => "ES", "phone_code" => "", "masking" => ""],
            ["name" => "Sri Lanka", "code" => "LK", "phone_code" => "", "masking" => ""],
            ["name" => "Soudan", "code" => "SD", "phone_code" => "", "masking" => ""],
            ["name" => "Suriname", "code" => "SR", "phone_code" => "", "masking" => ""],
            ["name" => "Svalbard et Jan Mayen", "code" => "SJ", "phone_code" => "", "masking" => ""],
            ["name" => "Swaziland", "code" => "SZ", "phone_code" => "", "masking" => ""],
            ["name" => "Suède", "code" => "SE", "phone_code" => "", "masking" => ""],
            ["name" => "Suisse", "code" => "CH", "phone_code" => "", "masking" => ""],
            ["name" => "République arabe syrienne", "code" => "SY", "phone_code" => "", "masking" => ""],
            ["name" => "Taiwan, Province de Chine", "code" => "TW", "phone_code" => "", "masking" => ""],
            ["name" => "Tadjikistan", "code" => "TJ", "phone_code" => "", "masking" => ""],
            ["name" => "Tanzanie, République-Unie de", "code" => "TZ", "phone_code" => "", "masking" => ""],
            ["name" => "Thaïlande", "code" => "TH", "phone_code" => "", "masking" => ""],
            ["name" => "Timor-Leste", "code" => "TL", "phone_code" => "", "masking" => ""],*/
            ["name" => "Togo", "code" => "TG", "phone_code" => "+ 228", "masking" => "99 99 99 99"],
            /*["name" => "Tokelau", "code" => "TK", "phone_code" => "", "masking" => ""],
            ["name" => "Tonga", "code" => "TO", "phone_code" => "", "masking" => ""],
            ["name" => "Trinité-et-Tobago", "code" => "TT", "phone_code" => "", "masking" => ""],
            ["name" => "Tunisie", "code" => "TN", "phone_code" => "", "masking" => ""],
            ["name" => "Turquie", "code" => "TR", "phone_code" => "", "masking" => ""],
            ["name" => "Turkménistan", "code" => "TM", "phone_code" => "", "masking" => ""],
            ["name" => "Îles Turks et Caicos", "code" => "TC", "phone_code" => "", "masking" => ""],
            ["name" => "Tuvalu", "code" => "TV", "phone_code" => "", "masking" => ""],
            ["name" => "Uganda", "code" => "UG", "phone_code" => "", "masking" => ""],
            ["name" => "Ukraine", "code" => "UA", "phone_code" => "", "masking" => ""],
            ["name" => "Émirats arabes unis", "code" => "AE", "phone_code" => "", "masking" => ""],
            ["name" => "Royaume-Uni", "code" => "GB", "phone_code" => "", "masking" => ""],
            ["name" => "États-Unis", "code" => "US", "phone_code" => "", "masking" => ""],
            ["name" => "Îles mineures éloignées des États-Unis", "code" => "UM", "phone_code" => "", "masking" => ""],
            ["name" => "Uruguay", "code" => "UY", "phone_code" => "", "masking" => ""],
            ["name" => "Uzbekistan", "code" => "UZ", "phone_code" => "", "masking" => ""],
            ["name" => "Vanuatu", "code" => "VU", "phone_code" => "", "masking" => ""],
            ["name" => "Venezuela", "code" => "VE", "phone_code" => "", "masking" => ""],
            ["name" => "Viet Nam", "code" => "VN", "phone_code" => "", "masking" => ""],
            ["name" => "Îles vierges britanniques", "code" => "VG", "phone_code" => "", "masking" => ""],
            ["name" => "Îles vierges américaines", "code" => "VI", "phone_code" => "", "masking" => ""],
            ["name" => "Wallis et Futuna", "code" => "WF", "phone_code" => "", "masking" => ""],
            ["name" => "Sahara occidental", "code" => "EH", "phone_code" => "", "masking" => ""],
            ["name" => "Yémen", "code" => "YE", "phone_code" => "", "masking" => ""],
            ["name" => "Zambie", "code" => "ZM", "phone_code" => "", "masking" => ""],
            ["name" => "Zimbabwe", "code" => "ZW"]*/

        ];

        foreach ($countries as $key => $country) {
            Country::create($country);
        }
    }
}
